using System.Collections.Generic;

namespace SqlFM.Core.Dialects.KeywordSets
{
    /// <summary>
    /// ANSI SQL 关键字集合，作为所有方言的基础关键字库。
    /// 借鉴 sqlfluff 的 ansi 方言关键字定义，涵盖 SQL-92/SQL:1999/SQL:2003 核心关键字。
    /// </summary>
    public static class AnsiKeywords
    {
        /// <summary>ANSI SQL 保留关键字</summary>
        public static readonly HashSet<string> Reserved = new HashSet<string>
        {
            // SQL-92 Core
            "SELECT", "FROM", "WHERE", "INSERT", "UPDATE", "DELETE", "CREATE", "DROP", "ALTER",
            "GRANT", "REVOKE", "COMMIT", "ROLLBACK", "BEGIN", "END", "DECLARE", "SET",
            "IF", "ELSE", "WHILE", "FOR", "CASE", "WHEN", "THEN", "ELSE", "END",
            "AND", "OR", "NOT", "IN", "EXISTS", "BETWEEN", "LIKE", "IS", "NULL",
            "AS", "ON", "JOIN", "INNER", "LEFT", "RIGHT", "FULL", "OUTER", "CROSS",
            "GROUP", "ORDER", "HAVING", "LIMIT", "OFFSET", "UNION", "ALL", "DISTINCT",
            "WITH", "RECURSIVE", "VALUES", "INTO", "TABLE", "VIEW", "INDEX", "CONSTRAINT",
            "PRIMARY", "KEY", "FOREIGN", "REFERENCES", "UNIQUE", "CHECK", "DEFAULT",
            "CASCADE", "RESTRICT", "NO", "ACTION", "DEFERRABLE", "INITIALLY",
            "IMMEDIATE", "DEFERRED", "RETURNING",
            "BOOLEAN", "CHARACTER", "VARCHAR", "INTEGER", "BIGINT", "SMALLINT",
            "NUMERIC", "DECIMAL", "REAL", "DOUBLE", "FLOAT", "DATE", "TIME",
            "TIMESTAMP", "INTERVAL", "BLOB", "CLOB", "ARRAY", "MULTISET",
            "TRUE", "FALSE", "UNKNOWN",
            "ANY", "SOME", "OVER", "PARTITION", "WINDOW", "ROW", "ROWS", "RANGE",
            "PRECEDING", "FOLLOWING", "CURRENT", "UNBOUNDED", "EXCLUDE",
            "FETCH", "NEXT", "PRIOR", "ABSOLUTE", "RELATIVE", "SCROLL", "NOSCROLL",
            "AFTER", "BEFORE", "EXCEPT", "INTERSECT", "CORRESPONDING",
            "CONTINUE", "RETURN", "TEST", "UNDER", "CONSTRUCTOR",
            "ZONE", "ONLY", "ROUTINE", "FUNCTION", "PROCEDURE", "MODULE",
            "TRIGGER", "EXECUTE", "CALL", "USAGE", "DOMAIN", "CHAR",
            "NATIONAL", "NCHAR", "NVARCHAR", "BIT", "VARYING",
            "ESCAPE", "TRANSACTION", "WORK", "ISOLATION", "LEVEL",
            "READ", "WRITE", "COMMITTED", "UNCOMMITTED", "REPEATABLE", "SERIALIZABLE",
            "PUBLIC", "SESSION", "USER", "CURRENT_USER", "CURRENT_DATE",
            "CURRENT_TIME", "CURRENT_TIMESTAMP", "LOCALTIME", "LOCALTIMESTAMP",
            "SESSION_USER", "SYSTEM_USER", "ROLE", "AUTHORIZATION",
            "ASSERTION", "PERMISSION", "PRIVILEGES", "COLLATE", "COLLATION",
            "CATALOG", "SCHEMA", "AUTHORIZATION", "TRANSFORM", "TRANSFORMS",
            "TYPE", "METHOD", "SPECIFIC", "INSTANCE", "SUBTYPE",
            "LOCATOR", "REFER", "CAST", "CONVERT", "LIKE", "SIMILAR",
            "SUBSTRING", "TRIM", "POSITION", "OVERLAY", "NORMALIZE",
            "EXTRACT", "OCCURRENCES_REGEX", "POSITION_REGEX", "SUBSTRING_REGEX",
            "UPPER", "LOWER", "TRANSLATE", "OVERRIDE", "SIGNAL", "RESET",
            "RESIGNAL", "SQLEXCEPTION", "SQLWARNING", "NOTFOUND", "SQLSTATE",
            "DIAGNOSTICS", "MESSAGE", "STACKED", "CONDITION",
            "SECTION", "COUNT", "SUM", "AVG", "MIN", "MAX",
            "OF", "AT", "TO", "BY", "FOR"
        };

        /// <summary>ANSI SQL 非保留关键字</summary>
        public static readonly HashSet<string> Unreserved = new HashSet<string>
        {
            "ABORT", "ABS", "ACCORDING", "ACOS", "ACTION", "ADA", "ADD",
            "ADMIN", "AFTER", "AGGREGATE", "ALIAS", "ALLOCATE", "ANALYZE",
            "ANSI", "APPEND", "ARCHIVE", "ARE", "ASC", "ASENSITIVE",
            "ATTRIBUTE", "ATTRIBUTES", "AUTO_INCREMENT", "AVG",
            "BASE", "BASENAME", "BEFORE", "BERNOULLI", "BINARY", "BIT_LENGTH",
            "BLOCK", "BOTH", "BOTTOM", "BREADTH", "BULK", "BY",
            "C", "CACHE", "CALLED", "CARDINALITY", "CASCADE", "CASCADED",
            "CHAIN", "CHARACTERISTICS", "CHARACTER_SET_CATALOG",
            "CHARACTER_SET_NAME", "CHARACTER_SET_SCHEMA",
            "CHECKPOINT", "CLASS", "CLASS_ORIGIN", "CLOB", "CLOSE",
            "COBOL", "COLLATION_CATALOG", "COLLATION_NAME", "COLLATION_SCHEMA",
            "COLLECT", "COLUMN", "COLUMNS", "COLUMN_NAME",
            "COMMIT", "COMMITTED", "CONCURRENTLY", "CONNECTION",
            "CONNECTION_NAME", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME",
            "CONSTRAINT_SCHEMA", "CONTAINS", "CONTENT", "CONTINUE",
            "CONTROL", "CONVERSION", "COPY", "CORR", "CORRESPONDING",
            "COS", "COSH", "COT", "COUNT", "COVAR_POP", "COVAR_SAMP",
            "CREATION", "CROSS", "CUBE", "CUME_DIST", "CURRENT",
            "CURRENT_PATH", "CURSOR", "CURSOR_NAME",
            "CYCLE", "DATA", "DATABASE", "DATE", "DATETIME_INTERVAL_CODE",
            "DATETIME_INTERVAL_PRECISION", "DAY", "DEALLOCATE", "DEC",
            "DECORRELATE", "DEFAULT", "DEFAULTS", "DEFERRABLE", "DEFERRED",
            "DEFINE", "DEFINED", "DEFINER", "DEGREE", "DEPTH", "DEREF",
            "DERIVED", "DESC", "DESCRIBE", "DESCRIPTOR", "DETERMINISTIC",
            "DIAGNOSTICS", "DISABLE", "DISCONNECT", "DISPATCH", "DOMAIN",
            "DOUBLE", "DROP", "DYNAMIC", "DYNAMIC_FUNCTION",
            "DYNAMIC_FUNCTION_CODE", "EACH", "ELEMENT", "EMPTY",
            "ENABLE", "ENCODING", "ENCRYPTED", "END-EXEC",
            "EQUALS", "ERROR", "ESCAPE", "EXCEPT", "EXCEPTION",
            "EXCLUDING", "EXCLUSIVE", "EXEC", "EXECUTE", "EXISTING",
            "EXP", "EXPLAIN", "EXTEND", "EXTERNAL", "EXTRACT",
            "FALSE", "FILTER", "FINAL", "FIRST", "FIRST_VALUE",
            "FLAG", "FLOAT", "FLOOR", "FOLLOWING", "FORCE", "FORTRAN",
            "FOUND", "FREE", "FREETEXT", "FREETEXTTABLE", "FROM",
            "FULL", "FUNCTION", "FUSION", "GENERAL", "GENERATED",
            "GET", "GLOBAL", "GO", "GOTO", "GRANT", "GRANTED",
            "GROUPING", "GROUPS", "HAVING", "HIERARCHY", "HOLD",
            "HOST", "HOUR", "IDENTITY", "IGNORE", "ILIKE", "IMMEDIATE",
            "IN", "INCLUDING", "INCREMENT", "INITIALLY", "INLINE",
            "INNER", "INOUT", "INPUT", "INSENSITIVE", "INSERT",
            "INSTANCE", "INSTANTIABLE", "INTERSECTION", "INTERVAL",
            "INTO", "INVOKER", "IS", "ISOLATION",
            "JOIN", "JSON_ARRAY", "JSON_ARRAYAGG", "JSON_EXISTS",
            "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_QUERY", "JSON_TABLE",
            "JSON_VALUE",
            "K", "KEY", "KEY_MEMBER", "KEY_TYPE", "LAG", "LAST",
            "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEFT",
            "LEVEL", "LIKE", "LN", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP",
            "LOCATOR", "LOG", "LOG10", "LOWER", "M", "MAP", "MATCH",
            "MATCHED", "MATCHES", "MAX", "MAXVALUE", "MEASURES",
            "MEMBER", "MERGE", "MESSAGE_LENGTH", "MESSAGE_OCTET_LENGTH",
            "MESSAGE_TEXT", "METHOD", "MIN", "MINUTE", "MINVALUE",
            "MOD", "MODIFIES", "MODULE", "MONTH", "MORE", "MUMPS",
            "NAME", "NAMES", "NATIONAL", "NCHAR", "NCLOB", "NEG",
            "NEW", "NEXT", "NFC", "NFD", "NFKC", "NFKD", "NO",
            "NONE", "NORMALIZE", "NORMALIZED", "NOT", "NTH_VALUE",
            "NTILE", "NULL", "NULLIF", "NUMERIC", "OBJECT",
            "OCCURRENCES_REGEX", "OF", "OFFSET", "OLD", "OVERRIDING",
            "OPTION", "OPTIONS", "OR", "ORDER", "ORDERING",
            "ORDINALITY", "OTHERS", "OUT", "OUTER", "OUTPUT",
            "OVER", "OVERLAPS", "OVERLAY", "OVERRIDING",
            "PAD", "PARAMETER", "PARAMETERS", "PARTIAL", "PARTITION",
            "PASCAL", "PASS", "PASSTHROUGH", "PAST", "PATH",
            "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK",
            "PERM", "PERMISSION", "PLACING", "PLI", "POSITION",
            "POSITION_REGEX", "POWER", "PRECEDING", "PRECISION",
            "PREPARE", "PRESERVE", "PRIMARY", "PRIOR", "PRIVILEGES",
            "PROCEDURE", "PUBLIC", "PYTHON", "QUALIFY", "QUARTER",
            "RANGE", "RANK", "READ", "READS", "REAL", "RECURSIVE",
            "REF", "REFERENCES", "REFERENCING", "REGR_AVGX",
            "REGR_AVGY", "REGR_COUNT", "REGR_ICOUNT",
            "REGR_INTERCEPT", "REGR_R2", "REGR_SXX",
            "REGR_SXY", "REGR_SYY", "RELATIVE", "RELEASE",
            "RENAME", "RESULT", "RETURN", "RETURNS", "REVOKE",
            "RIGHT", "ROLE", "ROLLBACK", "ROLLUP", "ROW",
            "ROWS", "ROW_NUMBER", "RULE", "SAVEPOINT", "SCHEMA",
            "SCROLL", "SEARCH", "SECOND", "SECTION", "SECURITY",
            "SENSITIVE", "SEQUENCE", "SERIALIZABLE", "SERVER",
            "SESSION", "SESSION_USER", "SET", "SETS", "SHOW",
            "SIMILAR", "SIZE", "SMALLINT", "SOME", "SOURCE",
            "SPACE", "SPECIFIC", "SPECIFICTYPE", "SQL",
            "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "SQRT",
            "STABLE", "START", "STATE", "STATEMENT", "STATIC",
            "STDDEV_POP", "STDDEV_SAMP", "SUBCLASS_ORIGIN",
            "SUBMULTISET", "SUBSTRING", "SUBSTRING_REGEX",
            "SUM", "SYMMETRIC", "SYSTEM", "SYSTEM_TIME",
            "SYSTEM_USER", "TABLE", "TABLESAMPLE", "TABLE_NAME",
            "TEMPORARY", "THEN", "TIES", "TIME", "TIMESTAMP",
            "TIMEZONE_HOUR", "TIMEZONE_MINUTE", "TO", "TOP",
            "TRAILING", "TRANSACTION", "TRANSACTIONS_ACTIVE",
            "TRANSACTIONS_COMMITTED", "TRANSACTIONS_ROLLEDBACK",
            "TRANSFORM", "TRANSFORMS", "TRANSLATE", "TRANSLATION",
            "TREAT", "TRIGGER", "TRIM", "TRIM_ARRAY", "TRUE",
            "TRUNCATE", "TYPE", "UESCAPE", "UNCOMMITTED",
            "UNDER", "UNDO", "UNIQUE", "UNKNOWN", "UNNEST",
            "UNTIL", "UPPER", "USAGE", "USER", "USER_DEFINED_TYPE_CATALOG",
            "USER_DEFINED_TYPE_NAME", "USER_DEFINED_TYPE_SCHEMA",
            "USING", "VALUE", "VALUES", "VALUE_OF", "VARBINARY",
            "VARCHAR", "VARYING", "VAR_POP", "VAR_SAMP", "VERSION",
            "VIEW", "WHEN", "WHENEVER", "WHERE", "WHILE",
            "WIDTH_BUCKET", "WINDOW", "WITH", "WITHIN", "WITHOUT",
            "WORK", "WRAPPER", "WRITE", "YEAR", "ZONE"
        };

        /// <summary>ANSI SQL 内置函数</summary>
        public static readonly HashSet<string> Functions = new HashSet<string>
        {
            "COUNT", "SUM", "AVG", "MIN", "MAX",
            "ABS", "CEIL", "CEILING", "FLOOR", "ROUND", "TRUNC", "TRUNCATE", "MOD",
            "POWER", "SQRT", "SIGN", "EXP", "LN", "LOG", "LOG10",
            "COS", "SIN", "TAN", "ACOS", "ASIN", "ATAN", "ATAN2", "COT",
            "COSH", "SINH", "TANH",
            "CAST", "CONVERT", "COALESCE", "NULLIF",
            "UPPER", "LOWER", "TRIM", "LTRIM", "RTRIM",
            "SUBSTRING", "LEFT", "RIGHT", "REPLACE", "TRANSLATE",
            "CHAR_LENGTH", "CHARACTER_LENGTH", "LENGTH", "OCTET_LENGTH",
            "POSITION", "CONCAT", "OVERLAY",
            "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP",
            "LOCALTIME", "LOCALTIMESTAMP",
            "EXTRACT", "DATE", "TIME", "TIMESTAMP",
            "ROW_NUMBER", "RANK", "DENSE_RANK", "PERCENT_RANK",
            "CUME_DIST", "NTILE", "LAG", "LEAD",
            "FIRST_VALUE", "LAST_VALUE", "NTH_VALUE",
            "STDDEV_POP", "STDDEV_SAMP", "VAR_POP", "VAR_SAMP",
            "PERCENTILE_CONT", "PERCENTILE_DISC",
            "CORR", "COVAR_POP", "COVAR_SAMP", "REGR_AVGX", "REGR_AVGY",
            "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SXX",
            "REGR_SXY", "REGR_SYY",
            "BIT_LENGTH", "OCCURRENCES_REGEX", "POSITION_REGEX",
            "SUBSTRING_REGEX", "TRANSLATE_REGEX", "TRIM_ARRAY",
            "NORMALIZE", "TRANSFORMS",
            "GROUPING", "JSON_ARRAY", "JSON_ARRAYAGG",
            "JSON_OBJECT", "JSON_OBJECTAGG", "JSON_QUERY",
            "JSON_TABLE", "JSON_VALUE", "JSON_EXISTS"
        };

        /// <summary>ANSI SQL 数据类型</summary>
        public static readonly HashSet<string> DataTypes = new HashSet<string>
        {
            "INT", "INTEGER", "SMALLINT", "BIGINT", "TINYINT",
            "NUMERIC", "DECIMAL", "DEC", "REAL", "DOUBLE", "FLOAT",
            "BIT", "BIT_VARYING", "VARBIT",
            "CHAR", "CHARACTER", "VARCHAR", "CHARACTER_VARYING", "CHAR_VARYING",
            "NCHAR", "NATIONAL_CHARACTER", "NVARCHAR", "NATIONAL_CHARACTER_VARYING",
            "TEXT", "CLOB", "NCLOB", "BLOB", "BINARY", "VARBINARY", "BINARY_VARYING",
            "BOOLEAN", "BOOL",
            "DATE", "TIME", "TIMESTAMP", "TIMESTAMPTZ", "TIMESTAMP_WITH_TIME_ZONE",
            "TIME_WITH_TIME_ZONE", "INTERVAL",
            "ARRAY", "MULTISET", "ROW", "TABLE", "CURSOR", "REF",
            "JSON", "UUID", "XML",
            "SERIAL", "BIGSERIAL", "SMALLSERIAL", "AUTOINCREMENT"
        };
    }
}
